### ISSUE TITLE
Error with diagramsnet

### ISSUE THREAD

**Issue by Heiss** [asciidoctor/asciidoctor-kroki#424]
Hey,

i want to reference to a diagram generated by diagramsnet. So i create a drawio-file with diagrams.net and want to include it with the following snippet (which works).

```asciidoc
.Software architecture
diagramsnet::images/architecture.drawio[]
```

But if i add an id, so i can reference it later, then i get an 400 Internal Server Error from the kroki server. In the logs i can see, that the request now contains `?id=testref` at the end.

```asciidoc
.Software architecture
[[testref]]
diagramsnet::images/architecture.drawio[]

<<testref>>
```

This error is reproducable, if i type this:
```asciidoc
diagramsnet::images/architecture.drawio[title="Software architecture",id="testref"]

<<testref>>
```

If i use another service, in my case excalidraw, the exact same setup works like expected and no error is returned.

I hope you guys can follow my explanation and can fix my problem.

Thank you and have a great day.
Heiss

**Comment by ggrossetie** [comment]
I think we should fix this issue upstream. Even if diagrams.net service/endpoint does not support options it should ignore them (not produce a 400).

Please open an issue at yuzutech/kroki.

Thanks!

**Comment by Heiss** [comment]
Thank you for your quick response.

**Comment by ggrossetie** [comment]
Fixed upstream!
