### ISSUE TITLE
asciidoctor-kroki `ruby-0.9.1` (latest available) does not work with asciidoctor `2.0.22`

### ISSUE THREAD

**Issue by dduportal** [asciidoctor/asciidoctor-kroki#444]
Hi! As caught in https://github.com/asciidoctor/docker-asciidoctor/pull/437/, asciidoctor-kroki `ruby-0.9.1` (latest available) does not work with asciidoctor `2.0.22`.

- The culprit code seems to be: https://github.com/asciidoctor/asciidoctor-kroki/blob/1a35570d3f675d5250ff6c3471e9f5f489c675f1/ruby/lib/asciidoctor/extensions/asciidoctor_kroki/extension.rb#L297
- [asciidoctor `2.0.22` changelog](https://github.com/asciidoctor/asciidoctor/releases/tag/v2.0.22) clearly states this is deprecated to support upcoming Ruby 3.4.

@mojavelinux recommens to use `String#pack` but I'm not good enough in Ruby to understand what it means (searching https://ruby-doc.org/3.3.0/String.html does not show me tangible result) so I'm opening an issue whether a PR.

**Comment by mojavelinux** [comment]
The equivalent code can be found here: https://github.com/ruby/base64/blob/master/lib/base64.rb#L328-L333

It would look something like this:

```rb
str = ([str].pack 'm0').tr '+/', '-_'
```

**Comment by mojavelinux** [comment]
The extension shouldn't be relying on Asciidoctor to load a library from stdlib (and base64 is being removed in 3.4 anyway).

**Comment by ggrossetie** [comment]
That's weird to remove such as useful and tiny lib from stdlib 🤔 
I wonder why they thought it was a good idea.

**Comment by mojavelinux** [comment]
I totally agree that it was a very unwise choice.

**Comment by siaccarino** [comment]
A require 'base64' in extension.rb fixes the issues for me

**Comment by jaskij** [comment]
In the meantime, is a workaround available?

**Comment by mojavelinux** [comment]
You can also just add `-r base64` when invoking the **asciidoctor** command.

**Comment by dduportal** [comment]
Thanks @ggrossetie , I'll watch when the new release will be available to ensure the Docker image of `asciidoctor` picks it!

**Comment by dduportal** [comment]
Hello @ggrossetie @mojavelinux could we release a new version of `asciidoctor-kroki` to ensure the fix is available (as it is blocking https://github.com/asciidoctor/docker-asciidoctor/pull/437)?

As I'm requesting this, I do not mind to help if needed (and possible in term of permissions of course)

**Comment by ggrossetie** [comment]
Sorry forgot to push the release, 0.10.0 should be available soon

**Comment by ggrossetie** [comment]
@dduportal Could you please give it a try https://rubygems.org/gems/asciidoctor-kroki/versions/0.10.0 ?

**Comment by dduportal** [comment]
> @dduportal Could you please give it a try https://rubygems.org/gems/asciidoctor-kroki/versions/0.10.0 ?

- The automation detected the new version and opened a PR which was successful(ly merged): https://github.com/asciidoctor/docker-asciidoctor/pull/441
- https://github.com/asciidoctor/docker-asciidoctor/pull/437 is now working as expected with this new asciidoctor-kroki version.

Many thanks @ggrossetie !

**Comment by ggrossetie** [comment]
Awesome 👍🏻
