### ISSUE TITLE
README: Mistake in include example for Antora

### ISSUE THREAD

**Issue by bartkl** [asciidoctor/asciidoctor-kroki#458]
Hi,

The example code under _Includes_ under _References and includes with Antora_ seems to use the wrong type of block. The `---` should be replaced with `....` (like in the example above it).

Thanks for this great extension,
Bart

**Comment by ggrossetie** [comment]
Hey! 
Both are valid but I tend to prefer `....` (over `----`).
Feel free to open a pull request to update the README.

**Comment by bartkl** [comment]
I am very new to AsciiDoc, AsciiDoctor and Antora, but I had to change that syntax or otherwise it wouldn't work properly.  Any idea why? Maybe it's not important, but I like to learn.

I'll make a PR!

**Comment by ggrossetie** [comment]
> I'll make a PR!

Thanks !
